#pragma once

#define PERSPECTIVE_SIDESCROLLER 0
#define PERSPECTIVE_TOPDOWN 1

#define GAME_PERSPECTIVE PERSPECTIVE_TOPDOWN

#if GAME_PERSPECTIVE == PERSPECTIVE_SIDESCROLLER
#define PLATFORMER_MOVEMENT
#define PLAYER_ENABLE_JUMP
#endif