#pragma once

#define NET_MODE_TURN_BASED_DETERMINISTIC   1
#define NET_MODE_SERVER_AUTH                2
#define NET_MODE_GGPO                       3
#define NET_MODE_LOCKSTEP                   4

#define NET_MODE NET_MODE_GGPO

#if NET_MODE == NET_MODE_TURN_BASED_DETERMINISTIC

#define NET_MODE_TURN_BASED_RUN
//#define NET_MODE_TURN_BASED_INPUT
//#define NET_MODE_TURN_BASED_REGULAR_UPDATES

#endif

#if NET_MODE == NET_MODE_GGPO
//#define NET_MODE_GGPO_SLIDING_WINDOW
#endif

#ifdef _WEB
#define NET_USE_WEBRTC
#else
//#define NET_USE_WEBRTC
#endif

#define NET_USE_RANDOM
#define NET_ALLOW_LATE_JOIN
#define NET_LATE_JOIN_REMOVE_BOT
#define NET_LATE_JOIN_ADD_BOT
//#define NET_ALLOW_OBSERVERS
//#define NET_FILL_WITH_BOTS
//#define NET_USE_READY

#define NET_SYNC_OLD_STATE
#define NET_SYNC_HISTORY_FRAMES 1
