
#include "Runtime/RuntimeCommon.h"

#include "Runtime/UI/UIDef.refl.meta.h"

#include "StormData/StormDataJson.h"

STORM_DATA_DEFAULT_CONSTRUCTION_IMPL(UIElementDataBase);
STORM_DATA_DEFAULT_CONSTRUCTION_IMPL(UIDefInputVariable);
STORM_DATA_DEFAULT_CONSTRUCTION_IMPL(UIDefEquation);
STORM_DATA_DEFAULT_CONSTRUCTION_IMPL(UIDefOutputEquation);
STORM_DATA_DEFAULT_CONSTRUCTION_IMPL(UIDef);
STORM_DATA_DEFAULT_CONSTRUCTION_IMPL(UIDefChild);
