#pragma once

#define LOBBY_VERSION 1000

#define ENABLE_BAN_LIST
#define ENABLE_BOTS
#define ENABLE_CHANNELS
#define ENABLE_REWARDS
#define ENABLE_SERVER_LIST
#define ENABLE_SQUADS
#define ENABLE_WELCOME_INFO

#define ENABLE_AUTH_NONE
#define ENABLE_AUTH_STEAM

#define DATABASE_NAME "sbe"

#define STEAM_WEB_API_KEY ""
#define STEAM_APP_ID ""
