#pragma once

#define BASE_PORT        26000

#define DEFAULT_GAME_PORT   BASE_PORT + 10

#define LOBBY_USER_PORT     BASE_PORT + 1
#define LOBBY_GAME_PORT     BASE_PORT + 2
#define LOBBY_BOT_PORT      BASE_PORT + 3
#define LOBBY_LB_PORT       BASE_PORT + 4
#define NODE_NETWORK_PORT   BASE_PORT + 5
#define COORDINATOR_PORT    BASE_PORT + 6

#define DIST_SERVER_PORT    BASE_PORT + 7

