
cd $PROJECT_DIR
mkdir build
cd build

cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TOOLS=ON -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_PREFIX_PATH=$QT_DIR -DCLANG_HEADER_PATH=$CLANG_HEADER_PATH $PROJECT_DIR
make
cd $PROJECT_DIR

