
cd %PROJECT_DIR%
mkdir build
cd build

cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Debug -DEXPORT_TEST=ON -DBUILD_TOOLS=ON -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_PREFIX_PATH=%QT_DIR% -DCLANG_HEADER_PATH=%CLANG_HEADER_PATH% %PROJECT_DIR%
start StormBrewerEngine.sln
cd %PROJECT_DIR%
